install:
    - sudo wget -O boost_1_67_0.tar.bz2 https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
    - sudo tar --bzip2 -xf boost_1_67_0.tar.bz2
    - cd boost_1_67_0/
    - ./bootstrap.sh --with-libraries=filesystem,system
    - ./b2 link=shared threading=multi variant=release
